lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(int:JWT_TOKEN_TTL)%'
    
    # Token extraction configuration
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: false
        query_parameter:
            enabled: false
    
    # REMOVE the encoder configuration completely
    # The bundle will use the default encoder automatically
    
    # User identity field
    user_id_claim: email
    
    # Clock skew for token validation
    clock_skew: 60
