# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/public':
            allow_origin: ['*']
            allow_methods: ['GET', 'OPTIONS']
        '^/api/auth':
            allow_origin: ['%env(FRONTEND_URL)%']
            allow_methods: ['POST', 'OPTIONS']
        '^/api':
            allow_origin: ['%env(FRONTEND_URL)%']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
